CREATE ROLE ${app_db_user} LOGIN PASSWORD '${app_db_password}' NOSUPERUSER NOCREATEDB NOCREATEROLE NOINHERIT;

GRANT CONNECT ON DATABASE ${flyway:database} TO ${app_db_user};
GRANT USAGE ON SCHEMA retry_lab TO ${app_db_user};
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA retry_lab TO ${app_db_user};
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA retry_lab TO ${app_db_user};

ALTER DEFAULT PRIVILEGES IN SCHEMA retry_lab
    GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO ${app_db_user};
ALTER DEFAULT PRIVILEGES IN SCHEMA retry_lab
    GRANT USAGE, SELECT ON SEQUENCES TO ${app_db_user};
